In [27]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [28]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [29]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [30]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

dataset

In [31]:
indep=dataset[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=dataset[['charges']]

In [32]:
indep

      age  sex_male     bmi  children  smoker_yes
0      19         0  27.900         0           1
1      18         1  33.770         1           0
2      28         1  33.000         3           0
3      33         1  22.705         0           0
4      32         1  28.880         0           0
...   ...       ...     ...       ...         ...
1333   50         1  30.970         3           0
1334   18         0  31.920         0           0
1335   18         0  36.850         0           0
1336   21         0  25.800         0           0
1337   61         0  29.070         0           1

[1338 rows x 5 columns]

In [33]:
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [34]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [35]:
X_train

      age  sex_male    bmi  children  smoker_yes
482    18         0  31.35         0           0
338    50         1  32.30         1           1
356    46         1  43.89         3           0
869    25         0  24.30         3           0
182    22         1  19.95         3           0
...   ...       ...    ...       ...         ...
763    27         1  26.03         0           0
835    42         1  35.97         2           0
1216   40         1  25.08         0           0
559    19         1  35.53         0           0
684    33         0  18.50         1           0

[892 rows x 5 columns]

In [36]:
X_train.shape

(892, 5)

In [37]:
y_train

         charges
482    1622.1885
338   41919.0970
356    8944.1151
869    4391.6520
182    4005.4225
...          ...
763    3070.8087
835    7160.3303
1216   5415.6612
559    1646.4297
684    4766.0220

[892 rows x 1 columns]

In [38]:
y_train.shape

(892, 1)

In [39]:
X_test

      age  sex_male     bmi  children  smoker_yes
578    52         1  30.200         1           0
610    47         0  29.370         1           0
569    48         1  40.565         2           1
1034   61         1  38.380         0           0
198    51         0  18.050         0           0
...   ...       ...     ...       ...         ...
261    20         0  26.840         1           1
1271   25         0  34.485         0           0
1313   19         0  34.700         2           1
2      28         1  33.000         3           0
405    52         0  38.380         2           0

[446 rows x 5 columns]

In [40]:
X_test.shape

(446, 5)

In [41]:
y_test

          charges
578    9724.53000
610    8547.69130
569   45702.02235
1034  12950.07120
198    9644.25250
...           ...
261   17085.26760
1271   3021.80915
1313  36397.57600
2      4449.46200
405   11396.90020

[446 rows x 1 columns]

In [42]:
y_test.shape

(446, 1)

In [43]:
from sklearn.ensemble import AdaBoostRegressor
regressor = AdaBoostRegressor(random_state=0, n_estimators=100)
regressor.fit(X_train, y_train)#y=W*x1+b0 for this equation we got value for b1 and bo

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

AdaBoostRegressor(n_estimators=100, random_state=0)

In [49]:
# Viewing the b1 and bo value
estimators=regressor.estimators_
print("estimators={}".format(estimators))
estimator_weights_=regressor.estimator_weights_
print("estimator_weights_={}".format(estimator_weights_))

estimators=[DecisionTreeRegressor(max_depth=3, random_state=209652396), DecisionTreeRegressor(max_depth=3, random_state=2134232591), DecisionTreeRegressor(max_depth=3, random_state=1144052126), DecisionTreeRegressor(max_depth=3, random_state=1867050542), DecisionTreeRegressor(max_depth=3, random_state=1165234930), DecisionTreeRegressor(max_depth=3, random_state=555744234), DecisionTreeRegressor(max_depth=3, random_state=380481120)]
estimator_weights_=[1.99248428 1.19967907 0.43296014 0.41523495 0.13707842 0.11859582
 0.93720793 0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.        ]

In [45]:
y_pred=regressor.predict(X_test)

In [46]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [47]:
r_score

0.8494579300295323