In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#print(np.__version__)

In [3]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset.head(133)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [5]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [12]:
from sklearn.neural_network  import MLPClassifier

In [ ]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'activation':['identity', 'logistic', 'tanh', 'relu'],
              'solver':['lbfgs', 'sgd', 'adam'],
              'learning_rate':['constant','invscaling','adaptive'],
              'max_iter':[10,100,1000]} 



grid = GridSearchCV(MLPClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 108 candidates, totalling 540 fits

GridSearchCV(estimator=MLPClassifier(), n_jobs=-1,
             param_grid={'activation': ['identity', 'logistic', 'tanh', 'relu'],
                         'learning_rate': ['constant', 'invscaling',
                                           'adaptive'],
                         'max_iter': [10, 100, 1000],
                         'solver': ['lbfgs', 'sgd', 'adam']},
             scoring='f1', verbose=3)

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:
print(grid.best_params_)

{'activation': 'relu', 'learning_rate': 'adaptive', 'max_iter': 1000, 'solver': 'adam'}

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_activation,param_learning_rate,param_max_iter,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.099551,0.073226,0.009288,0.000951,identity,constant,10,lbfgs,"{'activation': 'identity', 'learning_rate': 'c...",0.687500,0.722222,0.500000,0.888889,0.882353,0.736193,0.143549,34
1,0.026710,0.006280,0.007987,0.001229,identity,constant,10,sgd,"{'activation': 'identity', 'learning_rate': 'c...",0.461538,0.600000,0.468085,0.727273,0.711111,0.593601,0.113941,77
2,0.025026,0.004463,0.007617,0.000471,identity,constant,10,adam,"{'activation': 'identity', 'learning_rate': 'c...",0.687500,0.592593,0.384615,0.837209,0.765957,0.653575,0.157201,73
3,0.013085,0.001762,0.009491,0.004263,identity,constant,100,lbfgs,"{'activation': 'identity', 'learning_rate': 'c...",0.687500,0.722222,0.500000,0.888889,0.882353,0.736193,0.143549,34
4,0.154214,0.012071,0.007973,0.000748,identity,constant,100,sgd,"{'activation': 'identity', 'learning_rate': 'c...",0.620690,0.625000,0.484848,0.888889,0.882353,0.700356,0.159459,64
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103,0.194094,0.002176,0.007879,0.000742,relu,adaptive,100,sgd,"{'activation': 'relu', 'learning_rate': 'adapt...",0.571429,0.625000,0.516129,0.823529,0.848485,0.676914,0.134616,71
104,0.220546,0.004454,0.007329,0.000524,relu,adaptive,100,adam,"{'activation': 'relu', 'learning_rate': 'adapt...",0.750000,0.789474,0.702703,0.894737,0.972973,0.821977,0.098547,11
105,0.619152,0.314563,0.007530,0.000240,relu,adaptive,1000,lbfgs,"{'activation': 'relu', 'learning_rate': 'adapt...",0.764706,0.820513,0.772727,0.810811,0.833333,0.800418,0.026972,18
106,1.576950,0.132516,0.008171,0.000975,relu,adaptive,1000,sgd,"{'activation': 'relu', 'learning_rate': 'adapt...",0.709677,0.789474,0.628571,0.918919,0.944444,0.798217,0.120538,21
107,0.696218,0.149490,0.006153,0.001927,relu,adaptive,1000,adam,"{'activation': 'relu', 'learning_rate': 'adapt...",0.833333,0.820513,0.780488,0.926829,0.972973,0.866827,0.071538,1

In [18]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'activation': 'relu', 'learning_rate': 'adaptive', 'max_iter': 1000, 'solver': 'adam'}: 0.9180821729616219

In [19]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [ 5 44]]

In [20]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.94      0.93      0.93        85
           1       0.88      0.90      0.89        49

    accuracy                           0.92       134
   macro avg       0.91      0.91      0.91       134
weighted avg       0.92      0.92      0.92       134

In [21]:
table_pr=pd.DataFrame()

In [22]:
print(X_test)

     Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
168   29           148000            1
150   26            15000            0
393   60            42000            1
66    24            19000            1
240   42           149000            1

[134 rows x 3 columns]

In [23]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

In [24]:
table_pr.head(134)

     Age  Gender_male  Estimated_Salary  Actual  Predicted
132   30            1             87000       0          0
309   38            0             50000       0          0
341   35            1             75000       0          0
196   30            0             79000       0          0
246   35            0             50000       0          0
..   ...          ...               ...     ...        ...
168   29            1            148000       1          1
150   26            0             15000       0          0
393   60            1             42000       1          1
66    24            1             19000       0          0
240   42            1            149000       1          1

[134 rows x 5 columns]

In [ ]:
#table_pr.to_csv("cm.csv",index=False)

In [ ]:
#dataset['']
#dataset['Predicted']=grid_predictions

In [29]:
age_input=float(input("Age:"))
Salary_input=int(input("Salary:"))
Gender_Input=int(input("Gender Male 1 or False 0:"))

Age: 1
Salary: 1
Gender Male 1 or False 0: 1

In [30]:
Future_Prediction=grid.predict([[age_input,Salary_input,Gender_Input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

#####