In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#print(np.__version__)

In [3]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [4]:
dataset.head(133)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [5]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [6]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [7]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [8]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [9]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [11]:
from sklearn.linear_model import RidgeClassifier

In [12]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [13]:
from sklearn.model_selection import GridSearchCV

param_grid = {'solver':['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga', 'lbfgs'],
              'max_iter':[10,100,1000]} 



grid = GridSearchCV(RidgeClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
15 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1570, in fit
    super().fit(X, Y, sample_weight=sample_weight)
    ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 914, in fit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: 'lbfgs' solver can be used only when positive=True. Please use another solver.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.71552915 0.71552915 0.71552915 0.71552915 0.71552915 0.71249885
 0.71552915        nan 0.71552915 0.71552915 0.71552915 0.71552915
 0.71552915 0.71552915 0.71552915        nan 0.71552915 0.71552915
 0.71552915 0.71552915 0.71552915 0.71552915 0.71552915        nan]
  warnings.warn(

GridSearchCV(estimator=RidgeClassifier(), n_jobs=-1,
             param_grid={'max_iter': [10, 100, 1000],
                         'solver': ['auto', 'svd', 'cholesky', 'lsqr',
                                    'sparse_cg', 'sag', 'saga', 'lbfgs']},
             scoring='f1', verbose=3)

In [14]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [15]:
print(grid.best_params_)

{'max_iter': 10, 'solver': 'auto'}

In [16]:
table=pd.DataFrame.from_dict(re)

In [17]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_iter,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.511242,0.252940,0.019746,0.007453,10,auto,"{'max_iter': 10, 'solver': 'auto'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
1,0.376334,0.184092,0.008068,0.001231,10,svd,"{'max_iter': 10, 'solver': 'svd'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
2,0.006195,0.001467,0.008782,0.004014,10,cholesky,"{'max_iter': 10, 'solver': 'cholesky'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
3,0.007189,0.003143,0.008231,0.001604,10,lsqr,"{'max_iter': 10, 'solver': 'lsqr'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
4,0.005950,0.000595,0.006921,0.000986,10,sparse_cg,"{'max_iter': 10, 'solver': 'sparse_cg'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
5,0.164380,0.079173,0.009255,0.002078,10,sag,"{'max_iter': 10, 'solver': 'sag'}",0.62069,0.685714,0.484848,0.888889,0.882353,0.712499,0.155522,21
6,0.007625,0.001700,0.006660,0.001296,10,saga,"{'max_iter': 10, 'solver': 'saga'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
7,0.004350,0.002611,0.000000,0.000000,10,lbfgs,"{'max_iter': 10, 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
8,0.005149,0.000283,0.006903,0.001137,100,auto,"{'max_iter': 100, 'solver': 'auto'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
9,0.004785,0.000100,0.006225,0.000170,100,svd,"{'max_iter': 100, 'solver': 'svd'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
10,0.005418,0.001019,0.007267,0.000472,100,cholesky,"{'max_iter': 100, 'solver': 'cholesky'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
11,0.006932,0.002511,0.006897,0.000745,100,lsqr,"{'max_iter': 100, 'solver': 'lsqr'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
12,0.005584,0.001222,0.006745,0.000735,100,sparse_cg,"{'max_iter': 100, 'solver': 'sparse_cg'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
13,0.006846,0.001221,0.006601,0.000328,100,sag,"{'max_iter': 100, 'solver': 'sag'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
14,0.006299,0.001073,0.006414,0.000357,100,saga,"{'max_iter': 100, 'solver': 'saga'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
15,0.004097,0.001223,0.000000,0.000000,100,lbfgs,"{'max_iter': 100, 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
16,0.004989,0.000188,0.006543,0.000318,1000,auto,"{'max_iter': 1000, 'solver': 'auto'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
17,0.005461,0.000694,0.006555,0.000228,1000,svd,"{'max_iter': 1000, 'solver': 'svd'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
18,0.005751,0.000883,0.006665,0.000829,1000,cholesky,"{'max_iter': 1000, 'solver': 'cholesky'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
19,0.006125,0.001143,0.010143,0.005229,1000,lsqr,"{'max_iter': 1000, 'solver': 'lsqr'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
20,0.006381,0.001254,0.007112,0.001043,1000,sparse_cg,"{'max_iter': 1000, 'solver': 'sparse_cg'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
21,0.006869,0.001359,0.007813,0.001837,1000,sag,"{'max_iter': 1000, 'solver': 'sag'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
22,0.007106,0.001907,0.007860,0.002059,1000,saga,"{'max_iter': 1000, 'solver': 'saga'}",0.62069,0.685714,0.500000,0.888889,0.882353,0.715529,0.151142,1
23,0.004082,0.001040,0.000000,0.000000,1000,lbfgs,"{'max_iter': 1000, 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22

In [18]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'max_iter': 10, 'solver': 'auto'}: 0.8635810571647691

In [19]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[79  6]
 [12 37]]

In [20]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.87      0.93      0.90        85
           1       0.86      0.76      0.80        49

    accuracy                           0.87       134
   macro avg       0.86      0.84      0.85       134
weighted avg       0.87      0.87      0.86       134

In [21]:
table_pr=pd.DataFrame()

In [22]:
print(X_test)

     Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
168   29           148000            1
150   26            15000            0
393   60            42000            1
66    24            19000            1
240   42           149000            1

[134 rows x 3 columns]

In [23]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

In [24]:
table_pr.head(134)

     Age  Gender_male  Estimated_Salary  Actual  Predicted
132   30            1             87000       0          0
309   38            0             50000       0          0
341   35            1             75000       0          0
196   30            0             79000       0          0
246   35            0             50000       0          0
..   ...          ...               ...     ...        ...
168   29            1            148000       1          0
150   26            0             15000       0          0
393   60            1             42000       1          1
66    24            1             19000       0          0
240   42            1            149000       1          1

[134 rows x 5 columns]

In [25]:
#table_pr.to_csv("cm.csv",index=False)

In [26]:
#dataset['']
#dataset['Predicted']=grid_predictions

In [27]:
age_input=float(input("Age:"))
Salary_input=int(input("Salary:"))
Gender_Input=int(input("Gender Male 1 or False 0:"))

Age: 25
Salary: 1000
Gender Male 1 or False 0: 1

In [28]:
Future_Prediction=grid.predict([[age_input,Salary_input,Gender_Input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

#####