In [1]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Reading the Dataset
dataset = pd.read_csv('insurance_pre.csv')
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'charges'], dtype='object')

In [4]:
dataset=pd.get_dummies(dataset, dtype=int, drop_first=True)
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

dataset

In [5]:
indep=dataset[['age', 'sex_male', 'bmi', 'children', 'smoker_yes']]
dep=dataset[['charges']]

In [9]:
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import Ridge

param_grid = {'solver':['auto', 'svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga', 'lbfgs'],
'max_iter':[10,100,1000]}

grid = GridSearchCV(Ridge(), param_grid, refit = True, verbose = 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(indep, dep)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:516: FitFailedWarning:
15 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
15 fits failed with the following error:
Traceback (most recent call last):
  File "C:\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 859, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
    ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\sklearn\base.py", line 1365, in wrapper
    return fit_method(estimator, *args, **kwargs)
  File "C:\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 1248, in fit
    return super().fit(X, y, sample_weight=sample_weight)
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\anaconda3\Lib\site-packages\sklearn\linear_model\_ridge.py", line 914, in fit
    raise ValueError(
    ...<2 lines>...
    )
ValueError: 'lbfgs' solver can be used only when positive=True. Please use another solver.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1135: UserWarning: One or more of the test scores are non-finite: [0.74663526 0.74663526 0.74663526 0.74663526 0.74663526 0.74082532
 0.66890876        nan 0.74663526 0.74663526 0.74663526 0.74663526
 0.74663526 0.74663139 0.74662827        nan 0.74663526 0.74663526
 0.74663526 0.74663526 0.74663526 0.74662952 0.74662992        nan]
  warnings.warn(

GridSearchCV(estimator=Ridge(), n_jobs=-1,
             param_grid={'max_iter': [10, 100, 1000],
                         'solver': ['auto', 'svd', 'cholesky', 'lsqr',
                                    'sparse_cg', 'sag', 'saga', 'lbfgs']},
             verbose=3)

In [10]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))
print("The R_score value {}:".format(grid.best_score_))

The R_score value for best parameter {'max_iter': 10, 'solver': 'auto'}:
The R_score value 0.7466352593229096:

In [11]:
table=pd.DataFrame.from_dict(re)

In [12]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_iter,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006946,0.000322,0.004774,0.000424,10,auto,"{'max_iter': 10, 'solver': 'auto'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,1
1,0.021501,0.012735,0.011812,0.008698,10,svd,"{'max_iter': 10, 'solver': 'svd'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,7
2,0.010759,0.005150,0.005695,0.001422,10,cholesky,"{'max_iter': 10, 'solver': 'cholesky'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,1
3,0.011161,0.001811,0.010621,0.007875,10,lsqr,"{'max_iter': 10, 'solver': 'lsqr'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,13
4,0.016783,0.010705,0.005757,0.000743,10,sparse_cg,"{'max_iter': 10, 'solver': 'sparse_cg'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,10
5,0.014222,0.001512,0.005561,0.000864,10,sag,"{'max_iter': 10, 'solver': 'sag'}",0.756188,0.711150,0.756114,0.729074,0.751601,0.740825,0.017914,20
6,0.015944,0.004455,0.005577,0.001011,10,saga,"{'max_iter': 10, 'solver': 'saga'}",0.676239,0.654472,0.662199,0.666181,0.685453,0.668909,0.010847,21
7,0.007341,0.002186,0.000000,0.000000,10,lbfgs,"{'max_iter': 10, 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
8,0.007168,0.001223,0.004309,0.000154,100,auto,"{'max_iter': 100, 'solver': 'auto'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,1
9,0.006545,0.000332,0.004482,0.000146,100,svd,"{'max_iter': 100, 'solver': 'svd'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,7
10,0.008360,0.003541,0.004658,0.000620,100,cholesky,"{'max_iter': 100, 'solver': 'cholesky'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,1
11,0.011482,0.007146,0.009254,0.004510,100,lsqr,"{'max_iter': 100, 'solver': 'lsqr'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,13
12,0.010421,0.004501,0.006663,0.001834,100,sparse_cg,"{'max_iter': 100, 'solver': 'sparse_cg'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,10
13,0.027033,0.008258,0.010340,0.005470,100,sag,"{'max_iter': 100, 'solver': 'sag'}",0.761160,0.709085,0.774902,0.731734,0.756276,0.746631,0.023388,16
14,0.042370,0.011455,0.006005,0.001217,100,saga,"{'max_iter': 100, 'solver': 'saga'}",0.761183,0.709121,0.774811,0.731771,0.756256,0.746628,0.023351,19
15,0.007568,0.001392,0.000000,0.000000,100,lbfgs,"{'max_iter': 100, 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22
16,0.011673,0.004284,0.007041,0.001964,1000,auto,"{'max_iter': 1000, 'solver': 'auto'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,1
17,0.010278,0.003270,0.006154,0.001632,1000,svd,"{'max_iter': 1000, 'solver': 'svd'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,7
18,0.013564,0.009026,0.006156,0.001302,1000,cholesky,"{'max_iter': 1000, 'solver': 'cholesky'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,1
19,0.008873,0.001457,0.007219,0.004343,1000,lsqr,"{'max_iter': 1000, 'solver': 'lsqr'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,13
20,0.010336,0.003633,0.005754,0.001438,1000,sparse_cg,"{'max_iter': 1000, 'solver': 'sparse_cg'}",0.761152,0.709076,0.774943,0.731713,0.756292,0.746635,0.023404,10
21,0.016325,0.002117,0.005253,0.001057,1000,sag,"{'max_iter': 1000, 'solver': 'sag'}",0.761161,0.709079,0.774903,0.731736,0.756269,0.746630,0.023389,18
22,0.028952,0.004026,0.007094,0.003227,1000,saga,"{'max_iter': 1000, 'solver': 'saga'}",0.761181,0.709128,0.774819,0.731766,0.756256,0.746630,0.023351,17
23,0.006308,0.003405,0.000000,0.000000,1000,lbfgs,"{'max_iter': 1000, 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,22

In [13]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age: 42
BMI: 35
Children: 2
Sex Male 0 or 1: 0
Smoker Yes 0 or 1: 1

In [14]:
Future_Prediction=grid.predict([[age_input,sex_male_input,bmi_input,children_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[34736.54635537]

C:\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but Ridge was fitted with feature names
  warnings.warn(