In [34]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [35]:
#print(np.__version__)

In [36]:
# Reading the Dataset
dataset = pd.read_csv('Social_Network_Ads.csv')

In [37]:
dataset.head(133)

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
128  15722758    Male   30            17000          0
129  15792102  Female   26            84000          0
130  15675185    Male   31            58000          0
131  15801247    Male   33            31000          0
132  15725660    Male   30            87000          0

[133 rows x 5 columns]

In [38]:
dataset

      User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [39]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [40]:
dataset

      User ID  Age  EstimatedSalary  Purchased  Gender_Male
0    15624510   19            19000          0            1
1    15810944   35            20000          0            1
2    15668575   26            43000          0            0
3    15603246   27            57000          0            0
4    15804002   19            76000          0            1
..        ...  ...              ...        ...          ...
395  15691863   46            41000          1            0
396  15706071   51            23000          1            1
397  15654296   50            20000          1            0
398  15755018   36            33000          0            1
399  15594041   49            36000          1            0

[400 rows x 5 columns]

In [41]:
indep=dataset[['Age', 'EstimatedSalary','Gender_Male']]
dep=dataset['Purchased']

In [42]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [43]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train_= sc.fit_transform(X_train)
X_test_= sc.transform(X_test)

In [44]:
from sklearn.linear_model import SGDClassifier

In [45]:
#https://scikit-learn.org/stable/modules/model_evaluation.html#scoring-parameter

In [46]:
from sklearn.model_selection import GridSearchCV

param_grid = {'loss':['hinge', 'log_loss', 'modified_huber', 'squared_hinge', 'perceptron', 'squared_error', 'huber', 'epsilon_insensitive', 'squared_epsilon_insensitive'],
              'max_iter':[10,100,1000]} 



grid = GridSearchCV(SGDClassifier(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1') 
   
# fitting the model for grid search 
grid.fit(X_train_, y_train)

Fitting 5 folds for each of 27 candidates, totalling 135 fits

GridSearchCV(estimator=SGDClassifier(), n_jobs=-1,
             param_grid={'loss': ['hinge', 'log_loss', 'modified_huber',
                                  'squared_hinge', 'perceptron',
                                  'squared_error', 'huber',
                                  'epsilon_insensitive',
                                  'squared_epsilon_insensitive'],
                         'max_iter': [10, 100, 1000]},
             scoring='f1', verbose=3)

In [47]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test_) 
   

from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [48]:
print(grid.best_params_)

{'loss': 'modified_huber', 'max_iter': 100}

In [49]:
table=pd.DataFrame.from_dict(re)

In [50]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_loss,param_max_iter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006915,0.002362,0.010728,0.002352,hinge,10,"{'loss': 'hinge', 'max_iter': 10}",0.756757,0.692308,0.516129,0.829268,0.727273,0.704347,0.104354,3
1,0.003284,0.000314,0.008262,0.002095,hinge,100,"{'loss': 'hinge', 'max_iter': 100}",0.592593,0.647059,0.714286,0.818182,0.878049,0.730034,0.105548,2
2,0.004029,0.000657,0.006492,0.000262,hinge,1000,"{'loss': 'hinge', 'max_iter': 1000}",0.628571,0.631579,0.666667,0.823529,0.592593,0.668588,0.080941,9
3,0.004613,0.001490,0.009166,0.004378,log_loss,10,"{'loss': 'log_loss', 'max_iter': 10}",0.717949,0.604651,0.516129,0.818182,0.733333,0.678049,0.105727,7
4,0.004581,0.000474,0.007484,0.002641,log_loss,100,"{'loss': 'log_loss', 'max_iter': 100}",0.538462,0.600000,0.615385,0.695652,0.800000,0.649900,0.090248,11
5,0.005198,0.001215,0.008051,0.002305,log_loss,1000,"{'loss': 'log_loss', 'max_iter': 1000}",0.702703,0.755556,0.250000,0.842105,0.820513,0.674175,0.217705,8
6,0.003173,0.000279,0.006839,0.000535,modified_huber,10,"{'loss': 'modified_huber', 'max_iter': 10}",0.600000,0.714286,0.627451,0.755556,0.772727,0.694004,0.068794,5
7,0.005805,0.005130,0.007386,0.001713,modified_huber,100,"{'loss': 'modified_huber', 'max_iter': 100}",0.736842,0.580645,0.702703,0.864865,0.848485,0.746708,0.103856,1
8,0.003843,0.000608,0.007103,0.000954,modified_huber,1000,"{'loss': 'modified_huber', 'max_iter': 1000}",0.625000,0.666667,0.612245,0.680000,0.720000,0.660782,0.038851,10
9,0.003471,0.000231,0.007609,0.000799,squared_hinge,10,"{'loss': 'squared_hinge', 'max_iter': 10}",0.571429,0.739130,0.578947,0.705882,0.857143,0.690506,0.106765,6
10,0.004564,0.001327,0.006364,0.000192,squared_hinge,100,"{'loss': 'squared_hinge', 'max_iter': 100}",0.666667,0.697674,0.631579,0.727273,0.782609,0.701160,0.051690,4
11,0.003865,0.000454,0.006259,0.000331,squared_hinge,1000,"{'loss': 'squared_hinge', 'max_iter': 1000}",0.687500,0.594595,0.578947,0.652174,0.545455,0.611734,0.051259,13
12,0.006251,0.005311,0.007181,0.001253,perceptron,10,"{'loss': 'perceptron', 'max_iter': 10}",0.518519,0.541667,0.558140,0.277778,0.681818,0.515584,0.131670,17
13,0.003572,0.000416,0.006446,0.001101,perceptron,100,"{'loss': 'perceptron', 'max_iter': 100}",0.628571,0.606061,0.181818,0.755556,0.703704,0.575142,0.203760,14
14,0.003413,0.000147,0.006976,0.001158,perceptron,1000,"{'loss': 'perceptron', 'max_iter': 1000}",0.461538,0.682927,0.500000,0.789474,0.684211,0.623630,0.123490,12
15,0.003400,0.000374,0.007556,0.001288,squared_error,10,"{'loss': 'squared_error', 'max_iter': 10}",0.360000,0.333333,0.651163,0.678571,0.642857,0.533185,0.152982,16
16,0.004667,0.000296,0.006355,0.000131,squared_error,100,"{'loss': 'squared_error', 'max_iter': 100}",0.250000,0.461538,0.280000,0.000000,0.139535,0.226215,0.153312,27
17,0.005846,0.000551,0.006743,0.000668,squared_error,1000,"{'loss': 'squared_error', 'max_iter': 1000}",0.761905,0.521739,0.173913,0.433333,0.343750,0.446928,0.195026,22
18,0.004055,0.000637,0.007304,0.001149,huber,10,"{'loss': 'huber', 'max_iter': 10}",0.615385,0.523810,0.578947,0.000000,0.382979,0.420224,0.224493,24
19,0.003581,0.000401,0.006459,0.000208,huber,100,"{'loss': 'huber', 'max_iter': 100}",0.000000,0.416667,0.320000,0.750000,0.878049,0.472943,0.313402,21
20,0.003488,0.000263,0.006415,0.000557,huber,1000,"{'loss': 'huber', 'max_iter': 1000}",0.600000,0.679245,0.100000,0.711111,0.620690,0.542209,0.224657,15
21,0.004083,0.001275,0.007145,0.000882,epsilon_insensitive,10,"{'loss': 'epsilon_insensitive', 'max_iter': 10}",0.176471,0.387097,0.387097,0.488889,0.425532,0.373017,0.105082,25
22,0.004532,0.000350,0.006379,0.000206,epsilon_insensitive,100,"{'loss': 'epsilon_insensitive', 'max_iter': 100}",0.692308,0.769231,0.384615,0.200000,0.347826,0.478796,0.216190,20
23,0.004718,0.000400,0.007765,0.000806,epsilon_insensitive,1000,"{'loss': 'epsilon_insensitive', 'max_iter': 1000}",0.448980,0.577778,0.266667,0.697674,0.434783,0.485176,0.145139,18
24,0.004229,0.000820,0.006847,0.000507,squared_epsilon_insensitive,10,"{'loss': 'squared_epsilon_insensitive', 'max_i...",0.500000,0.545455,0.424242,0.142857,0.500000,0.422511,0.145144,23
25,0.006396,0.000949,0.007005,0.000568,squared_epsilon_insensitive,100,"{'loss': 'squared_epsilon_insensitive', 'max_i...",0.622222,0.146341,0.339623,0.800000,0.507042,0.483046,0.225542,19
26,0.004975,0.000753,0.005710,0.000917,squared_epsilon_insensitive,1000,"{'loss': 'squared_epsilon_insensitive', 'max_i...",0.535714,0.181818,0.592593,0.045455,0.461538,0.363424,0.212562,26

In [51]:

from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'loss': 'modified_huber', 'max_iter': 100}: 0.8662153518123668

In [52]:
print("The confusion Matrix:\n",cm)

The confusion Matrix:
 [[75 10]
 [ 8 41]]

In [53]:
print("The report:\n",clf_report)

The report:
               precision    recall  f1-score   support

           0       0.90      0.88      0.89        85
           1       0.80      0.84      0.82        49

    accuracy                           0.87       134
   macro avg       0.85      0.86      0.86       134
weighted avg       0.87      0.87      0.87       134

In [54]:
table_pr=pd.DataFrame()

In [55]:
print(X_test)

     Age  EstimatedSalary  Gender_Male
132   30            87000            1
309   38            50000            0
341   35            75000            1
196   30            79000            0
246   35            50000            0
..   ...              ...          ...
168   29           148000            1
150   26            15000            0
393   60            42000            1
66    24            19000            1
240   42           149000            1

[134 rows x 3 columns]

In [56]:
table_pr['Age']=X_test["Age"]
table_pr['Gender_male']=X_test["Gender_Male"]
table_pr['Estimated_Salary']=X_test["EstimatedSalary"]
table_pr['Actual']=y_test
table_pr['Predicted']=grid_predictions

In [57]:
table_pr.head(134)

     Age  Gender_male  Estimated_Salary  Actual  Predicted
132   30            1             87000       0          0
309   38            0             50000       0          0
341   35            1             75000       0          0
196   30            0             79000       0          0
246   35            0             50000       0          0
..   ...          ...               ...     ...        ...
168   29            1            148000       1          1
150   26            0             15000       0          0
393   60            1             42000       1          1
66    24            1             19000       0          0
240   42            1            149000       1          1

[134 rows x 5 columns]

In [58]:
#table_pr.to_csv("cm.csv",index=False)

In [59]:
#dataset['']
#dataset['Predicted']=grid_predictions

In [60]:
age_input=float(input("Age:"))
Salary_input=int(input("Salary:"))
Gender_Input=int(input("Gender Male 1 or False 0:"))

Age: 25
Salary: 10000
Gender Male 1 or False 0: 1

In [61]:
Future_Prediction=grid.predict([[age_input,Salary_input,Gender_Input]])# change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[1]

#####